const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({

    name:{
        type:String,
        required:true,
        unique:true
    },
    description:{
        type:String,
        required:true,
        default:''
    },
    brand:{
        type:String,
        required:true,
    },
    price:{
        type:Number,
        required:true,
        default:0
    },
    oldPrice:{
        type:Number,
        default:0
    },
    discountPercentage:{
        type:Number,
        default:0
    },
    discountPrice:{
        type:Number,
        default:0
    },
    color:{
        type:String,
        required:true
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'category',
        required:true
    },
    sizes:[{
        size:{
            type:String,
            enum:['XS','S','M','L','XL','XXL','Single Size'],
            required:true
        },
        stock:{
            type:Number,
            required:true,
            min:0,
            max:255
        }
    }],
    images:
        {
            type:Array,
            required:true
        },
    isDeleted:{
        type:Boolean,
        default:false
    },
    isOfferApplied:{
        type:Boolean,
        default:false
    },
    offerType:{
        type:String,
        enum:['productOffer','categoryOffer']
    },
    dateCreated:{
        type:Date,
        default:Date.now
    }
}) 

module.exports = mongoose.model('product',productSchema);